GET http://localhost:3000/

###
GET http://localhost:3000/api/users 

###
GET http://localhost:3000/api/users/60c3e7a4cad64e0536d1799d

###

POST http://localhost:3000/api/users/post
content-type: application/json

{
    "name": "bla",
    "surname": "bla",
    "password": "bla"
}

###

DELETE http://localhost:3000/api/users/60c4bc1907b7bd213fd88c57

###

PATCH  http://localhost:3000/api/users/60c4c4d357b3ba2b524813cb
content-type: application/json

{
    "surname": "c",
    "password": "d"
}
