GET http://localhost:3000/

###
GET http://localhost:3000/api/users 

###
GET http://localhost:3000/api/users/60c769fba5f3922a73bd1b44

###

POST http://localhost:3000/api/users/post
content-type: application/json

{
    "name": "bla",
    "surname": "bla",
    "password": "bla"
}

###

DELETE http://localhost:3000/api/users/60c76d925eb8672c9232953c

###

PATCH  http://localhost:3000/api/users/60c769fba5f3922a73bd1b44
content-type: application/json

{
    "name": "jas",
    "surname": "pion"
}
